# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "CV"
  url = "files/CV_052025.pdf"
  weight = 10

[[main]]
    name = "Working papers"
    url = "#working-papers"
    weight = 20

[[main]]
    name = "Work in progress"
    url = "#work-in-progress"
    weight = 30
[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
    name = "Policy work"
    url = "#policy-writings"
    weight = 60

[[main]]
    name = "Teaching"
    url = "#teaching"
    weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/CV_052025.pdf"
#    weight = 70
